import type { Metadata } from "next";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Header from './header';
import Footer from './footer';
import { Merriweather } from "next/font/google";
config.autoAddCss = false


const merriweather = Merriweather({ subsets: ["latin"], weight: ["400", "700"] });


export const metadata: Metadata = {
  title: "Open Road Band Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={merriweather.className}>
      <body >
        
        <Header  />  
        {children}
        <Footer />
      </body>
    </html>
  );
}
